### PR TITLE
Add Intel 8085(A) definition(s)

### PR DESCRIPTION
**Pull request by schnepe2**
...including "unofficial" instructions: 
 DSUB     (Double Subtraction
 ARHL     (Arithmetic shift of H and L right
 RDEL     (Rotate D and E left through carry
 LDHI d8  (Load D and E with H and L plus immediate byte)
 LDSI d8  (Load D and E with SP plus immediate byte)
 RSTV     (Restart on overflow
 SHLX     (Store H and L indirect through D and E)
 JNX5 adr (Jump on not X5)
 LHLX     (Load H and L indirect through D and E)
 JX5      (Jump on X5)

### CODE REVIEW

**Comment by schnepe2** [comment]
This PR adds the definition for the Intel 8085(A) Microprocessor.
Intels 8080 Processors use the same opcodes (although lack some special I/O ones).
As the 8080 was made "Z80 compatible" the opcodes are similar, but were named different at Zilog (just for info, not that it matters much ;) )

**Comment by DigicoolThings** [comment]
Awesome.  A nice addition!  I never used the 8085 myself, but I do recall it as being a popular CPU, and making hardware design a little easier than with the earlier 8080.  
Thank you, I'll get your contribution committed and update the README with appropriate accreditation.

**Comment by schnepe2** [comment]
You don't  **have** to credit me in the README, but if you like you can do it 😄
I have to thank you for this simple - yet effective - tool! It gave me results very quickly.
I might still do a dedicated plugin for that CPU (so that StrToHex() also works), but that's another project for future-me.
Thanks again,
  Peter

**Comment by DigicoolThings** [comment]
Thanks Peter.  I'm glad it worked for you.  README has now been updated to mention your 8085(A) contribution.

I have been considering a re-write for some time, to improve on design aspect that bugs me.  But, so far I've been buried in other projects, and sometimes the "if it ain't broke", lowers the re-work priority! 

Can you elaborate on your StrToHex() comment.  Sorry, it's probably just that it's been a while since I worked with this.

**Comment by schnepe2** [comment]
> Can you elaborate on your StrToHex() comment.

Sure.
First, I took the wrong Method name (`StrToBytes` it is, sorry!)
It is the possibillity to edit the "decoded" part & HxD turns it into the (hex) bytes.
It's just the reverse process of decoding.
This is something one might like to to: Change a "`JMP $ACDC`" into "`JMP $007`" and dosn't like to think about endianess; or replace the "`JMP`" by a "`NOP`".

In essence: translation in both directions.

**Pull request merged**
